name: launch web3checks-backend ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Docker images
        run: |
          curl -XPOST -u "${{ secrets.CI_BOT_USERNAME }}:${{secrets.CI_BOT_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/LedgerHQ/web3checks-backend/dispatches --data '{"event_type": "on-demand-release"}'
