---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint

#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches:
      - main

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint
        uses: github/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          # since we are only interested in linting the allowlist JSON file
          VALIDATE_MARKDOWN: false
          VALIDATE_NATURAL_LANGUAGE: false
