name: merge-dapp-lists

on:
  workflow_call:
    inputs:
      message:
        description: "Commit message"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      message:
        description: "Commit message"
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge dApps assets lists
    permissions:
      contents: 'write'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_BOT_TOKEN }}
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: zulu:19

      - name: Setup gh packages for scala-cli
        run: |
          scala-cli --power config repositories.credentials "maven.pkg.github.com" value:PrivateToken env:GITHUB_TOKEN
          
      - name: Validate and merge assets lists
        #
        # Small hack to inject our GitHub packages token.
        #    https://github.com/VirtusLab/scala-cli/issues/1464
        #
        # perl -i -pe 's/{{ GITHUB_TOKEN }}/$ENV{GITHUB_TOKEN}/' .github/scripts/validate-and-merge-cli.scala
        run: |
          scala-cli config --dump
          scala-cli .github/scripts/validate-and-merge-cli.scala --main-class main -- all-dapp-allowlist.json

      - name: Commit and push merged list
        uses: EndBug/add-and-commit@v9
        with:
          add: "all-dapp-allowlist.json"
          author_name: ldg-github-ci
          author_email: none@ledger.fr
          default_author: github_actor
          message: "${{ inputs.message }}"
          push: true
