name: Unified dapp file
on:
  push:
    branches:
      - "*"
      - "!main"
    paths-ignore:
      - "allowlist.json"
      - "all-dapp-allowlist.json"

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Parser dapps files
    steps:
      - uses: actions/checkout@v2
      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: adopt:11
          apps: sbtn bloop ammonite
      - run: |
          amm scripts/validate-and-merge.sc --output all-dapp-allowlist.json
      - name: push file to main
        uses: EndBug/add-and-commit@v9
        with:
          add: "all-dapp-allowlist.json"
          committer_name: Github action
          committer_email: nobody@ledger.fr
          default_author: github_actor
          message: "Update unified dapp file"
          push: true
