name: merge-dapp-lists
on:
  push:
    branches:
      - "main"
    paths:
      - "dapp/**/*.json"

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge dApps assets lists
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: zulu:19
      - name: Validate and merge assets lists
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
        #
        # Small hack to inject our GitHub packages token.
        #    https://github.com/VirtusLab/scala-cli/issues/1464
        #
        run: |
          perl -i -pe 's/{{ GITHUB_TOKEN }}/$ENV{GITHUB_TOKEN}/' scripts/validate-and-merge-cli.sc
          scala-cli .github/scripts/validate-and-merge-cli.sc --main-class main -- all-dapp-allowlist.json

      - name: Commit and push merged list
        uses: EndBug/add-and-commit@v9
        with:
          add: "all-dapp-allowlist.json"
          default_author: github_actor
          message: "${{ github.event.push.head_commit.message }}"
          push: true
