name: trigger-merge-dapp-list

on:
  push:
    branches:
      - "main"
    paths:
      - "dapps/**/*.json"


jobs:
  dispatch:
    runs-on: ubuntu-latest
    needs: get_versions
    steps:
      - name: Dispatch QA workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: merge-dapp.yml
          token: ${{ secrets.CI_BOT_TOKEN }}
          inputs: '{"message": "${{ github.event.head_commit.message }}" }'

