name: trigger-merge-dapp-list

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/scripts/validate-and-merge-cli.scala"
      - ".github/workflows/merge-dapp.yml"
      - "dapps/**/*.json"
  workflow_dispatch:


jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch QA workflow
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: merge-dapp.yml
          token: ${{ secrets.CI_BOT_TOKEN }}
          inputs: '{"message": "${{ github.event.head_commit.message }}" }'
